import type { Metadata } from "next";
import {Nunito_Sans} from "next/font/google"
import "./globals.css";
import Header from "../components/header"
import Footer from "../components/footer"

const nunitoSans = Nunito_Sans({
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
